// smokestack-react/src/components/CigarForm.tsx
import React, { useState, useEffect } from 'react';


interface Cigar {
  id?: number;
  name: string;
  brand: string;
  strength: string;
  price: number;
}

interface Props {
  cigar?: Cigar;
  onSubmit: (data: Cigar) => void;
  onCancel: () => void;
}

const CigarForm: React.FC<Props> = ({ cigar, onSubmit, onCancel }) => {
  const [formData, setFormData] = useState<Cigar>({
    name: '',
    brand: '',
    strength: '',
    price: 0,
  });

  useEffect(() => {
    if (cigar) {
      setFormData(cigar);
    }
  }, [cigar]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'price' ? parseFloat(value) : value,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="mb-3">
        <label className="form-label">Name</label>
        <input type="text" name="name" value={formData.name} onChange={handleChange} className="form-control" required />
      </div>

      <div className="mb-3">
        <label className="form-label">Brand</label>
        <input type="text" name="brand" value={formData.brand} onChange={handleChange} className="form-control" required />
      </div>

      <div className="mb-3">
        <label className="form-label">Strength</label>
        <select name="strength" value={formData.strength} onChange={handleChange} className="form-control" required>
          <option value="">Select Strength</option>
          <option value="Mild">Mild</option>
          <option value="Medium">Medium</option>
          <option value="Full">Full</option>
        </select>
      </div>

      <div className="mb-3">
        <label className="form-label">Price</label>
        <input type="number" name="price" value={formData.price} onChange={handleChange} className="form-control" required />
      </div>

      <div className="d-flex justify-content-end">
        <button type="submit" className="btn btn-success me-2">Save</button>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button>
      </div>
    </form>
  );
};

export default CigarForm;

// smokestack-ui/src/app/components/cigar-form/cigar-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CigarService, Cigar } from '../../services/cigar.service';

@Component({
  selector: 'app-cigar-form',
  templateUrl: './cigar-form.component.html'
})
export class CigarFormComponent implements OnInit {
  cigar: Cigar = { name: '', brand: '', strength: '', price: 0 };
  isEdit = false;

  constructor(
    private cigarService: CigarService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEdit = true;
      this.cigarService.getById(+id).subscribe({
        next: data => (this.cigar = data),
        error: err => console.error('Error loading cigar', err)
      });
    }
  }

  onSubmit() {
    if (this.isEdit) {
      this.cigarService.update(this.cigar.id!, this.cigar).subscribe({
        next: () => this.router.navigate(['/']),
        error: err => console.error('Error updating cigar', err)
      });
    } else {
      this.cigarService.create(this.cigar).subscribe({
        next: () => this.router.navigate(['/']),
        error: err => console.error('Error creating cigar', err)
      });
    }
  }
}

<div class="card p-4">
  <h3>{{ isEdit ? 'Edit Cigar' : 'Add New Cigar' }}</h3>

  <form (ngSubmit)="onSubmit()" #cigarForm="ngForm">
    <div class="mb-3">
      <label class="form-label">Name</label>
      <input type="text" class="form-control" required [(ngModel)]="cigar.name" name="name" />
    </div>

    <div class="mb-3">
      <label class="form-label">Brand</label>
      <input type="text" class="form-control" required [(ngModel)]="cigar.brand" name="brand" />
    </div>

    <div class="mb-3">
      <label class="form-label">Strength</label>
      <select class="form-select" [(ngModel)]="cigar.strength" name="strength" required>
        <option value="">Select Strength</option>
        <option>Mild</option>
        <option>Medium</option>
        <option>Full</option>
      </select>
    </div>

    <div class="mb-3">
      <label class="form-label">Price</label>
      <input type="number" class="form-control" required [(ngModel)]="cigar.price" name="price" />
    </div>

    <button type="submit" class="btn btn-success me-2">{{ isEdit ? 'Update' : 'Create' }}</button>
    <button type="button" class="btn btn-secondary" routerLink="/">Cancel</button>
  </form>
</div>
